### PR TITLE
Update to iojs 2.3.1

### PR DESCRIPTION
**Pull request by frankhale**
Update to iojs v2.3.1. I had a lot of issues doing this, please let me know if this is correct.

### CODE REVIEW

**Comment by frankhale** [comment]
This should be fine. I just compiled Electron 0.28.3 against this and it worked work me.

**Comment by hokein** [comment]
@frankhale 
Looks like you are using the `master` branch of iojs to do upgrade work. If you want to update to v2.3.1, I suppose you should use the [v2.3.1 tag branch](https://github.com/nodejs/io.js/releases/tag/v2.3.1) of iojs.

**Comment by frankhale** [comment]
Anyway to fix this without me having to delete my fork, refork and do the work all over again? I actually did rebase against the tag v.2.3.1 but apparently I did something wrong?

**Comment by frankhale** [comment]
I'll fix this and resubmit

**Pull request closed without merging**
