### PR TITLE
patches for Electron 

### PR DESCRIPTION
**Pull request by deepak1556**
Went by this minimal route as other options were to use our `NodeDebugger` from `atom::Nodemain` but it depends on `base::commandLine` to parse args. Another was to replicate `node::ParseDebugOpt` and start the debugger agent directly which didnt seem a nice idea. any thoughts ?

Related https://github.com/atom/atom-shell/pull/1416

### CODE REVIEW

**Comment by deepak1556** [comment]
@zcbenz will this do https://gist.github.com/deepak1556/9d98a181735ecf8d7366 , thanks!

**Comment by deepak1556** [comment]
patch for module lookup https://gist.github.com/deepak1556/b6986a78ef25fd3c4098 , related https://github.com/atom/atom-shell/issues/1390

**Comment by zcbenz** [comment]
> patch for module lookup https://gist.github.com/deepak1556/b6986a78ef25fd3c4098 , related atom/electron#1390

Path merged to https://github.com/atom/node/commit/769925318334c0fe0370799bc85f54f1ee7138ce.

**Comment by zcbenz** [comment]
> patch for module lookup https://gist.github.com/deepak1556/b6986a78ef25fd3c4098 , related atom/electron#1390

We should filter out those paths on electron side. The number of patches in this repo should be as minimal as possible.

**Comment by deepak1556** [comment]
cool will do, Thanks!

**Pull request closed without merging**
