### PR TITLE
Update iojs to version 2.3.1

### PR DESCRIPTION
**Pull request by frankhale**
Update iojs to version 2.3.1

### CODE REVIEW

**Comment by frankhale** [comment]
This is a much cleaner patch and everything went pretty smoothly to rebase against the v.2.3.1 tag. If there are still problems please let me know. Thanks!

**Comment by frankhale** [comment]
I'm currently testing my app against Electron 0.28.3 and iojs 2.3.1 and so far everything is fine. If you see any glaring issues with this patch please let me know.

**Comment by zcbenz** [comment]
Thanks, the pull request to use io.js v2.3.1 has been created at #2077.

**Comment by frankhale** [comment]
I'm a little upset that my PR was not merged and you chose to do the work again. Was there something wrong with the work I had done? I took a lot of time to make sure it was right so any feedback you can give would be much appreciated.

**Comment by frankhale** [comment]
I'd like to help out in the future keep this fork updated with upstream but am going to need your feedback so that my PRs are at the highest possible level and what the project requires. Thanks!

**Comment by zcbenz** [comment]
@frankhale I rebased your rebased commits into the atom-iojs branch directly instead of merging this, so there is not feedback on GitHub website. I need to make sure the git history is liner and merging with GitHub website would mess things up, keeping liner history is super important otherwise it would be more and more painful when doing future io.js updates, sorry I didn't make clear.

**Comment by frankhale** [comment]
No worries, just wanted to make sure that effort was not being duplicated for no reason. Thank you for taking the time to explain. This makes very good sense! Thank you!

**Comment by frankhale** [comment]
Just one last note on this. Maybe it wasn't apparent from the 2 previous attempts at PR's for 2.3.1 but this PR was against a fresh fork of atom/node. There wouldn't have been any crazy git history. I fetched upstream, merged 2.3.1 and then rebased the default branch against and fixed up a couple patch conflicts. There were no code changes for the node integration to it to work. 

But thanks for updating so quickly to 2.3.1. It'll be nice to have Electron as up to date as possible with iojs.

**Pull request closed without merging**
